const path = require('path');
const os = require('os');

const ROOT = path.resolve(__dirname, '..', '..');
const PORT = process.env.PORT || 3000;

const MOBILE_UA = 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Mobile/15E148 Safari/604.1';

const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
const OPENAI_BASE_URL = process.env.OPENAI_BASE_URL || 'https://api.groq.com/openai/v1';
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'openai/gpt-oss-120b';
const OPENAI_IMPORT_MODEL = process.env.OPENAI_IMPORT_MODEL
  || (/groq\.com/i.test(OPENAI_BASE_URL) ? 'openai/gpt-oss-20b' : OPENAI_MODEL);
const DEFAULT_OPENAI_VISION_MODEL = 'meta-llama/llama-4-scout-17b-16e-instruct';
const OPENAI_VISION_MODEL = process.env.OPENAI_VISION_MODEL || DEFAULT_OPENAI_VISION_MODEL;
const OPENAI_TRANSCRIBE_MODEL = process.env.OPENAI_TRANSCRIBE_MODEL || 'gpt-4o-mini-transcribe';

const AI_PROMPT_MAX_CHARS = 12000;
const AI_IMAGE_MAX_BASE64_BYTES = 4 * 1024 * 1024;
const AI_RATE_LIMIT_WINDOW_MS = 10 * 60 * 1000;
const AI_RATE_LIMIT_MAX = 30;
const IMPORT_RATE_LIMIT_MAX = 10;
const AI_RATE_LIMIT_SWEEP_INTERVAL_MS = 60 * 1000;

const MEDIA_TMP_DIR = path.join(os.tmpdir(), 'kitchenmanager-media');
const MEDIA_MAX_VIDEO_BYTES = 80 * 1024 * 1024;
const MEDIA_DOWNLOAD_TIMEOUT_MS = 30000;
const MEDIA_FILE_TTL_MS = 60 * 60 * 1000;
const MEDIA_MAX_FRAME_COUNT = 3;
const MEDIA_MAX_FRAME_BYTES = 700 * 1024;
const RECIPE_IMPORT_MEDIA_CACHE_TTL_MS = 30 * 60 * 1000;

const MEDIA_TOO_LARGE_ERROR = new Error('MEDIA_TOO_LARGE');
const MEDIA_DOWNLOAD_ERROR = new Error('MEDIA_DOWNLOAD_FAILED');
const MEDIA_FFMPEG_ERROR = new Error('MEDIA_FFMPEG_FAILED');
const MEDIA_FRAME_TOO_LARGE_ERROR = new Error('MEDIA_FRAME_TOO_LARGE');
const MEDIA_FRAME_OCR_ERROR = new Error('MEDIA_FRAME_OCR_FAILED');
const MEDIA_TRANSCRIBE_ERROR = new Error('MEDIA_TRANSCRIBE_FAILED');
const MEDIA_EMPTY_TRANSCRIPT_ERROR = new Error('MEDIA_EMPTY_TRANSCRIPT');

module.exports = {
  ROOT,
  PORT,
  MOBILE_UA,
  OPENAI_API_KEY,
  OPENAI_BASE_URL,
  OPENAI_MODEL,
  OPENAI_IMPORT_MODEL,
  DEFAULT_OPENAI_VISION_MODEL,
  OPENAI_VISION_MODEL,
  OPENAI_TRANSCRIBE_MODEL,
  AI_PROMPT_MAX_CHARS,
  AI_IMAGE_MAX_BASE64_BYTES,
  AI_RATE_LIMIT_WINDOW_MS,
  AI_RATE_LIMIT_MAX,
  IMPORT_RATE_LIMIT_MAX,
  AI_RATE_LIMIT_SWEEP_INTERVAL_MS,
  MEDIA_TMP_DIR,
  MEDIA_MAX_VIDEO_BYTES,
  MEDIA_DOWNLOAD_TIMEOUT_MS,
  MEDIA_FILE_TTL_MS,
  MEDIA_MAX_FRAME_COUNT,
  MEDIA_MAX_FRAME_BYTES,
  RECIPE_IMPORT_MEDIA_CACHE_TTL_MS,
  MEDIA_TOO_LARGE_ERROR,
  MEDIA_DOWNLOAD_ERROR,
  MEDIA_FFMPEG_ERROR,
  MEDIA_FRAME_TOO_LARGE_ERROR,
  MEDIA_FRAME_OCR_ERROR,
  MEDIA_TRANSCRIBE_ERROR,
  MEDIA_EMPTY_TRANSCRIPT_ERROR
};
